### PR TITLE
Bug DCOS-9149: Adds timeout to spartan fetching Exhibitor data

### PR DESCRIPTION
**Pull request by GoelDeepak**

### CODE REVIEW

**Comment by GoelDeepak** [comment]
@sargun, This change is ready for review

**Comment by sargun** [comment]
Did you get a chance to test this with SIGSTOP'n exhibitor, or somehow artificially inducing a timeout.

**Comment by sargun** [comment]
Once this is tested, feel free to merge, and please update the hash in dcos/dcos.

**Comment by GoelDeepak** [comment]
Test steps:
1. [local] compiled src/spartan_config_loader_server.erl (exported get_masters_exhibitor for testing)
2. [local] scp _build/default/lib/spartan/ebin/spartan_config_loader_server.beam core@<master-ip>:
3. [master] sudo cp _build/default/lib/spartan/ebin/spartan_config_loader_server.beam /opt/mesosphere/active/spartan/spartan/lib/spartan/ebin/
4. [master] sudo /opt/mesosphere/active/spartan/spartan/bin/spartan_env remote_console
5. [master] l(spartan_config_loader_server)
6. [master] spartan_config_loader_server:get_masters_exhibitor().

Verified that if Exhibitor is SIGSTOP then above call hangs for <timeout> seconds.

**Comment by mesosphere-bot-deleteme-2016-04-18** [comment]
And does it return?

**Pull request merged**
